# Generated by Django 3.1 on 2020-08-31 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='date_sold',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
