# Generated by Django 3.1 on 2020-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200831_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
